### ISSUE TITLE
git push; recurring login

### ISSUE THREAD

**Issue by bhediathewolf** [githubschool/animated-invention#133]
Hi @hectorsector ,

So, every time I do git push, I have to basically login into my account with the email and the password, the everything, basically. Eric's push was quite automated in that regard. Will we be covering something on that later? If not, how do we achieve this? 
Just curious, is this related to the GPG keys Eric mentioned while going over his config?

Thanks,
S.

**Comment by hectorsector** [comment]
You can use the command `git config --global credential.helper ` and follow it with `osxkeychain` if you're on Mac OR `wincred` if you're on Windows. After that, the next time you type your credentials, it'll be saved.

**Comment by hectorsector** [comment]
Some [documentation](https://help.github.com/articles/caching-your-github-password-in-git/) too!

**Comment by bhediathewolf** [comment]
Thank you. :smile:
