### ISSUE TITLE
Is that mandatory to use commandline?

### ISSUE THREAD

**Issue by othersideoflearning** [githubschool/animated-invention#137]
Do we have any other alternative for command line interface? Most of the people are not comfortable with command line so is there any other alternative for this.

Please explain how do we create different projects without using HTTP URL.

Thank you in advance.

**Comment by hectorsector** [comment]
@apallekonda today and tomorrow's class will exclusively use the command line, but you can interact with Git using other tools. Some suggestions can be found at https://git-scm.com/downloads/guis

**Comment by hectorsector** [comment]
I updated the link above ☝️
