### ISSUE TITLE
By Mistake I have merged my pull request, How can I get back that

### ISSUE THREAD

**Issue by othersideoflearning** [githubschool/animated-invention#150]

**Comment by hectorsector** [comment]
Sorry, I didn't see this earlier! You would create a new branch, and work off of that, @apallekonda. Branches are cheap and lightweight so there's no problem in creating new ones. Then, you'd create a new Pull Request with the branch.

**Comment by othersideoflearning** [comment]
I have done that but how can we revert previously merged one. Can you show that?

**Comment by hectorsector** [comment]
We'll show it tomorrow, but [here's a preview](https://github.github.io/training-manual/#_git_revert).

**Comment by othersideoflearning** [comment]
Thank you so much! 😃
