### ISSUE TITLE
Accidentally...

### ISSUE THREAD

**Issue by williamsmi** [githubschool/animated-invention#159]
I accidentally forked my branch...how can i reverse that? 💩

**Comment by hectorsector** [comment]
You mean you created a fork from the top-right? If you did, it's ok, it just isn't what we covered. Send me a link to what you're seeing and I'm happy to help. I probably won't answer until tomorrow but I'll get back to it.

**Comment by maria-williams** [comment]
Yes.  Don't really "see" anything, I just know that it said it was doing the fork.  Not sure where I can check to see the forked directory?

**Comment by williamsmi** [comment]
since this will be covered today, guess i'm ahead of the curve, so will not worry about this.  thanks!
