### ISSUE TITLE
What are 'bananas, with regard to the errors during pull request?

### ISSUE THREAD

**Issue by bhediathewolf** [githubschool/animated-invention#165]
Hi, @hectorsector 

Yesterday, during the pull requests we had a message that stated lack of bananas. What's it all about? 

Thanks,
S.

**Comment by hectorsector** [comment]
@bhediathewolf it wasn't intended to be there -- it came over from the source code I used to implement `teacherbot`. It was a simple project showing you how to create a bot to check for the word "banana" in a commit message, and mark a PR accordingly, and I extended the functionality to add collaborators. But I forgot to remove the 🍌's part!

**Comment by bhediathewolf** [comment]
Oh, that clears it up pretty well, thank you! Can you please share the bot repository? It would be fun to learn how that works. :smiley:

**Comment by hectorsector** [comment]
Here's the bot I'm using: https://github.com/probot/probot

Teacherbot, in particular, is still a little buggy (as you saw yesterday) so it's private right now. But I don't see a reason to keep it private when we go live with it (maybe in a couple of weeks?).

**Comment by bhediathewolf** [comment]
Thanks, that great. :+1:
