### ISSUE TITLE
Delete Branch that is not merged

### ISSUE THREAD

**Issue by cjcollins** [githubschool/animated-invention#171]
The revision is still available to diff,  but it isn't visible via lol. Can you explain what happens behind the scenes when this happens?

**Comment by hectorsector** [comment]
I'm not sure I understand -- what are you trying to compare, exactly? You can drag and drop a screenshot to the issue, as well.

**Comment by cjcollins** [comment]
Someone sitting with me deleted the branch that had the change to yellow. If he does the diff, the revision is there and diff works properly. when he executes oneline the revision does not show.

**Comment by hectorsector** [comment]
ah, that probably has to do with whether the the change has (a) been committed to the branch, and (b) whether that update was pushed up to GitHub (with a `git push`). If either (a) or (b) haven't been met, then you wouldn't see it on GitHub, even though you will still see it locally.

**Comment by cjcollins** [comment]
yes, it was committed and pushed. It was never merged before it was deleted. Now, even though the branch no longer exists, the revision still does. Found that a bit different from other version control systems. Was hoping to get a bit more information on how/why that works that way and if there is a way to "find" those orphaned revisions.

**Comment by hectorsector** [comment]
@cjcollins if you send me a screenshot and/or a link to where it exists up on GitHub I can look a little deeper.

**Comment by cjcollins** [comment]
He fixed his fork, but if you fork GitHub-games and delete stats-update before merging, that replicates it

**Comment by crichID** [comment]
@cjcollins just catching up with this discussion. I think the confusion could be that there was also a change on master to the same file. We were intentionally trying to generate a merge conflict so we did some funny business on the back end :wink:

If you delete a branch without merging it, a few things happen (depending on where you delete it):

- If you only delete the branch on GitHub.com, it doesn't automatically delete the branch on the local copy of the repository.
- If you only delete the branch locally, it still exists on GitHub.com (if it was pushed).

However, if you delete the branch both on GitHub.com and locally without merging it, those changes will not be a part of master. Does that make sense?

**Comment by cjcollins** [comment]
I understand all of that and is as expected. What seems odd is that the revision from the deleted branch is still available. I guess even though the branch is removed, the history of that branch still lives on, even if it is never merged to a still existing branch.

**Comment by crichID** [comment]
@cjcollins Ah - ok - I think I understand the question (I hope). So git doesn't immediately delete the refs behind the scenes when you delete the branch. You can actually see the old refs in `git reflog` for a limited time (~30 days if the branch was deleted). So if you have the commit ID, you can still look at the revision but it is technically no longer a part of your history and will be garbage collected.

**Comment by cjcollins** [comment]
@crichID - Exactly what I was looking for. 😃 

Thanks
