### ISSUE TITLE
Why did we do the revert in gh-pages and not a new branch?

### ISSUE THREAD

**Issue by TranslucentSabre** [githubschool/animated-invention#172]

**Comment by TranslucentSabre** [comment]
@hectorsector

**Comment by hectorsector** [comment]
No particular reason, we were simulating having to quickly roll back a commit made to `master`. You're right @TranslucentSabre, it'd be best practice to revert the change on a new branch and go through code review with a Pull Request.

**Comment by TranslucentSabre** [comment]
Thank you very much.
