### ISSUE TITLE
If you cannot hear me, please leave an issue at this URL and we can troubleshoot

### ISSUE THREAD

**Issue by githubteacher** [githubschool/animated-invention#2]
https://github.com/githubschool/animated-invention

**Comment by ghost** [comment]
I cannot hear you. I had to call in on the phone

**Comment by hectorsector** [comment]
@drczuckerman does the phone work now?

**Comment by hectorsector** [comment]
It looks like we've resolved this, so I'll go ahead and close this out. If anyone else has trouble with sound, feel free to reopen.
