### ISSUE TITLE
Hi there, I'm excited to be here--chiming in from Arizona

### ISSUE THREAD

**Issue by RaymondSHANG** [githubschool/animated-invention#22]
🐱 !

**Comment by RaymondSHANG** [comment]
Hello!

**Comment by RaymondSHANG** [comment]
Hello, no notice

**Comment by hectorsector** [comment]
Hi there! i'm closing this issue since you've now been added as a collaborator. If you have any further questions, open a new issue and I'll be glad to help you out 🎈 🙇
