### ISSUE TITLE
Archive Database

### ISSUE THREAD

**Issue by othersideoflearning** [githubschool/animated-invention#25]
Where can we find the past recorded webinar videos?
Please share the link so that we can refer in future if required.

**Comment by hectorsector** [comment]
@apallekonda a past recording of this particular class is available [here](https://www.youtube.com/playlist?list=PLg7s6cbtAD16Pgp6WIVfX4VsGI-xyWkMz).

**Comment by othersideoflearning** [comment]
I am looking for the GitHub desktop version videos. Could you please share that link.

**Comment by hectorsector** [comment]
GitHub Desktop was [recently updated](https://github.com/blog/2362-announcing-git-integration-for-atom-and-github-desktop-beta) and we've not yet had a webinar on that. You can, however, [sign up for the upcoming webinar](https://register.gotowebinar.com/register/1558584503189364226).

**Comment by othersideoflearning** [comment]
Thank you so much!
👍
