### ISSUE TITLE
Hello Githubbers! From Bucks, UK

### ISSUE THREAD

**Issue by dkwkuk** [githubschool/animated-invention#60]
Say hi all 👋

**Comment by dkwkuk** [comment]
Where do we go from here?

**Comment by hectorsector** [comment]
👋 it looks like the bot didn't get to respond to you, but you _are_ a collaborator, so feel free to close out this issue!

**Comment by hectorsector** [comment]
Hi there! i'm closing this issue since you've now been added as a collaborator. If you have any further questions, open a new issue and I'll be glad to help you out 🎈 🙇
