### ISSUE TITLE
Is there a way to change the name of a branch?

### ISSUE THREAD

**Issue by Sisyphus67** [githubschool/animated-invention#73]
I jumped the gun on branch creation and didn't mention a location in the title.  Is there a way to hide my inability to follow instructions?

**Comment by hectorsector** [comment]
@Sisyphus67 on your command line, yes, but not on the web UI. The easiest thing to do is to delete and create a new one. A branch is just a pointer to a time in history on the back-end, so there's no hard to doing that.

**Comment by Sisyphus67** [comment]
OK, thanks!
