### ISSUE TITLE
@Hectorsector

### ISSUE THREAD

**Issue by pateldip84** [githubschool/animated-invention#74]
I am new to GIT and GITHUB. One thing i noticed is i was unable to create the branch. Once i created an issue i was able to create the branch. what makes this possible? why does it behave the way it did?

**Comment by pateldip84** [comment]
@Hectorsector I am new to GIT and GITHUB. One thing i noticed is i was unable to create the branch. Once i created an issue i was able to create the branch. what makes this possible? why does it behave the way it did?

**Comment by hectorsector** [comment]
@pateldip84 good question! You were not a collaborator before. We've set up the `teacherbot` to grant you collaborator access after commenting on an issue, so after that you _are_ a collaborator and able to create a branch

**Comment by hectorsector** [comment]
In a real life scenario, you'd either (a) request collaborator access from the project owner so you can create branches, or (b) use a fork-and-pull workflow, which we'll go over tomorrow

**Comment by pateldip84** [comment]
thanks. That is pretty cool automation.
