### ISSUE TITLE
regards from CT... hello

### ISSUE THREAD

**Issue by jsundet** [githubschool/animated-invention#75]
:1234:

**Comment by jsundet** [comment]
I guess I'm not a collaborator.  I don't seem to be creating a branch.

@hectorsector

**Comment by hectorsector** [comment]
@jsundet I can see that you are a collaborator. Can you show me a screenshot of what happens when you try to create a branch? Heads up, if you're using Internet Explorer you'll have to use Chrome or Firefox instead. For screenshots, you can just save it as a file and drag/drop it into the text box.

**Comment by jsundet** [comment]
@hectorsector Seems to be okay now.  I have a branch.
