### ISSUE TITLE
Collaboration on branches?

### ISSUE THREAD

**Issue by bhediathewolf** [githubschool/animated-invention#76]
@hectorsector 
Hi,

So, can people collaborate/contribute to other user's branches? 
Since, we are branching Master to submit changes without messing up the production, does every user indeed branch their own version? 
Also, Can branches be merged together before to the Master?

Thanks,
S.

**Comment by hectorsector** [comment]
So many good questions!

> So, can people collaborate/contribute to other user's branches?

Yes, we are all equal collaborators and can all collaborate on each other's branches. 

> Since, we are branching Master to submit changes without messing up the production, does every user indeed branch their own version?

Yes and no. Technically, a branch is nothing more than a pointer to history. So each of our branches are just pointers to the same point in history. However, once we start adding our own code to our branches, we'll have, in practice, our own unique versions of the project. 

> Also, Can branches be merged together before to the Master?

Yes. However, best practice is to merge from (and to) `master` .

**Comment by bhediathewolf** [comment]
Thanks!
