### ISSUE TITLE
Why I do not have the "setting" tab on the animated-invention page?

### ISSUE THREAD

**Issue by baojason** [githubschool/animated-invention#77]
I noticed that I do not have the setting tab like the teacher's screen on animated-invention page, is there a way to turn it on?

**Comment by bhediathewolf** [comment]
Settings tab is only for the admins, or those who created the repository. The idea is to limit people who can delete a project, unintentionally or otherwise.

**Comment by baojason** [comment]
Thanks, @bhediathewolf
