### ISSUE TITLE
Creating new folder/directory in a repository I do not own

### ISSUE THREAD

**Issue by pw185004** [githubschool/animated-invention#80]
@hectorsector 

I need to create a new subdirectory for another group of workload files under workload_tests folder/directory so that the different workload tests are not mingled.
I am not the admin for this repository, just a contributor - how can I create this new folder/directory?

**Comment by hectorsector** [comment]
@pw185004 locally is easiest (we'll get to that over the rest of today), but on the web UI, you can go right to `Create new file` and then type in the directory name followed by a forward slash, and then the file name of the first file you'd like to add: `new_directory/new_file.txt`, for example. Git will require at least one file (it won't recognize empty directories).

**Comment by pw185004** [comment]
Aha!  That’s why my previous attempts have been failing ☺

Paul R. Williams
office: 678-303-2776
cell:    404-435-7219
email: Paul.Williams@Teradata.com
Stone Mountain, GA
Dual Active Engineering
[Description: cid:3397191658_12905663]

**Comment by hectorsector** [comment]
PS - you can click the pencil to edit the last comment and remove some of your identifiable info 😉
