### ISSUE TITLE
Can you please tell me what will be covered in the last half hour of class today?

### ISSUE THREAD

**Issue by jeremypollack** [githubschool/animated-invention#82]
@hectorsector 

Hello!  I have a meeting at 2:30 and will be missing the last half hour of class.  Can you please tell me what will be covered from 2:30 to 3:00 so that I may complete the day's training at home later?  If you have a link to the class materials, I'll be happy to follow along.  I want to make sure I'm prepared for tomorrow's class!

Thank you!  😄

**Comment by hectorsector** [comment]
@jeremypollack sure, there's a training manual and videos.

It can differ every class, but usually the last half hour we cover these sections from the manual:
- [Viewing Local Project History](https://github.github.io/training-manual/#_local_history)
- [Streamlining Your Workflow with Aliases](https://github.github.io/training-manual/#_create_alias)

Corresponding videos are at:
- [Syncing the Local Repository](https://www.youtube.com/watch?v=CY2LBiOnBgo&list=PLg7s6cbtAD16Pgp6WIVfX4VsGI-xyWkMz&index=7)
- [Logs and Creating Aliases](https://www.youtube.com/watch?v=i66UhpEoYL0&list=PLg7s6cbtAD16Pgp6WIVfX4VsGI-xyWkMz&index=8)

**Comment by jeremypollack** [comment]
Awesome -- thank you!
