### ISSUE TITLE
git submodule

### ISSUE THREAD

**Issue by QikeLi** [githubschool/animated-invention#83]
@hectorsector Would it be possible to cover the git submodule? 🙏

**Comment by hectorsector** [comment]
@QikeLi I'll pass it along for Eric to cover near the end, but it's not usually in the scope of our class, so it'll be superficial. What are you trying to do? I may be able to link you to some resources.

**Comment by QikeLi** [comment]
Thank you, Hector! I would like to be able to manage some sub-projects under a big project.  🙇

**Comment by hectorsector** [comment]
[This cheatsheet](https://services.github.com/on-demand/downloads/submodule-vs-subtree-cheat-sheet/) may be helpful!
