### ISSUE TITLE
My git config --global --list only returns the user.email and user.name

### ISSUE THREAD

**Issue by RaymondSHANG** [githubschool/animated-invention#84]
Is this a problem? Why they are different from 'git config --list' which returns all information
@hectorsector

**Comment by hectorsector** [comment]
@RaymondSHANG Eric has some specific configs that he's already set from prior uses. For now, we're just interested in `user.name` and `user.email`.

**Comment by hectorsector** [comment]
[Here's](https://git-scm.com/docs/git-config) some documentation if you're interested in all the possibilities.

**Comment by RaymondSHANG** [comment]
Got it, thanks.

**Comment by RaymondSHANG** [comment]
Eric's terminal settings of display seems cool. Could he share the PS1 please?:-)
@hectorsector

**Comment by hectorsector** [comment]
sure, I think he's using zsh, but we'll ping him so he can drop it after class

@hollenberry 👀 🙏

**Comment by githubteacher** [comment]
https://github.com/sorin-ionescu/prezto
