### ISSUE TITLE
push issues

### ISSUE THREAD

**Issue by pw185004** [githubschool/animated-invention#89]
@hectorsector pw185004@WUSPW185004-63P MINGW64 ~/My Documents/GitHub Training/animated-invention (Paul-Atlanta)
$ git push Paul-Atlanta.md
fatal: Invalid gitfile format: Paul-Atlanta.md
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pw185004** [comment]
Latest command line info:
pw185004@WUSPW185004-63P MINGW64 ~/My Documents/GitHub Training/animated-invention (Paul-Atlanta)
$ git status
On branch Paul-Atlanta
Your branch is ahead of 'origin/Paul-Atlanta' by 2 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Paul-Atlanta.md

no changes added to commit (use "git add" and/or "git commit -a")

pw185004@WUSPW185004-63P MINGW64 ~/My Documents/GitHub Training/animated-invention (Paul-Atlanta)
$ git add Paul-Atlanta.md

pw185004@WUSPW185004-63P MINGW64 ~/My Documents/GitHub Training/animated-invention (Paul-Atlanta)
$ git status
On branch Paul-Atlanta
Your branch is ahead of 'origin/Paul-Atlanta' by 2 commits.
  (use "git push" to publish your local commits)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   Paul-Atlanta.md


pw185004@WUSPW185004-63P MINGW64 ~/My Documents/GitHub Training/animated-invention (Paul-Atlanta)
$ git commit Paul-Atlanta.md -m "Added new tags"
[Paul-Atlanta 97ed82d] Added new tags
 1 file changed, 4 insertions(+), 4 deletions(-)

pw185004@WUSPW185004-63P MINGW64 ~/My Documents/GitHub Training/animated-invention (Paul-Atlanta)
$

**Comment by pw185004** [comment]
@hectorsector I have resolved it - needed to re-login for the push.
All is OK now :-)

**Comment by hectorsector** [comment]
Glad you got it taken care of -- apologies for the delay!
